### ISSUE TITLE
Módulo control de rutinas Web

### ISSUE THREAD

**Issue by MLizano** [vmonge/UGYM_Mobile_App#20]

**Comment by OscarMorera** [comment]
Reunirse con el instructor del gimnasio para conocer el procedimiento de confección de las  rutinas (identificación de los ejercicios individuales -por ejemplo "remo con polea" y "tirón de espalda"-; como se combinan para hacer ejercicios elaborados para trabajar músculos relacionados-por ejemplo trapecio, romboide mayor, deltoide -); números de combinaciones).

**Comment by MLizano** [comment]
esta issue pertenece a otro al Project de Movil
